### ISSUE TITLE
Sending E-Commerce data doesn't work

### ISSUE THREAD

**Issue by jasonvdzeeuw** [revolunet/angular-google-analytics#103]
Hello,

I've tried sending E-commerce data with multiple accounts and single account. 
None of it seems to work.

I've tried it with the native google code, and that works.
So I've looked further and made a simple angular app, including just this module with the default settings.
When I log all the steps, everything seems to work correct, but there's no new outgoing request.

So  I have no third party code, just a clean little project, but still no success.

**Comment by justinsa** [comment]
Can you share the project and version of the code being used? Are you using e-commerce or enhanced e-commerce? I need to know how things have been setup to help you determine what might be wrong.

**Comment by AVee** [comment]
The page below can be used to show this behaviour with the current angular-google-analytics.js. (After a valid analytics account is set...)
```html
    <!doctype html>
    <html ng-app="App">
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular.min.js"></script>
        <script src="./angular-google-analytics.js"></script>
    
        <script>
            angular.module('App', ['angular-google-analytics'])
            .config(function (AnalyticsProvider) {
                AnalyticsProvider.setAccount('<GA-ACCOUNT>');
                AnalyticsProvider.useECommerce(true, true);
                AnalyticsProvider.setCurrency('EUR');
                AnalyticsProvider.logAllCalls(true);
            })
            .controller('AppController', function (Analytics) {
                // This gets tracked
                Analytics.trackPage('/foobar');

                // This doesn't get tracked
                Analytics.addProduct('sku-2', 'Test Product 2', 'Category-1', 'Brand 2', 'variant-3', '2499', '1', 'FLAT10', '1'); 
                Analytics.trackCheckout(1, 'Visa');
                Analytics.addProduct('sku-2', 'Test Product 2', 'Category-1', 'Brand 2', 'variant-3', '1111', '1', 'WOMEN10', '1');
                Analytics.trackTransaction('T1234', 'Online Store - Web', '3333', '10', '200', 'FLAT10', '', '', '');
            });
        </script>
    </head>
    <body>
        <div ng-controller="AppController">
        </div>
    </body>
    </html>

**Comment by justinsa** [comment]
@AVee thanks for sharing this. @AVee and @jasonvdzeeuw, do either of you have a request chain that works when using the ga function directly? All calls made. I think there might be something amiss with how things are being configured during script tag creation for using e-commerce since the calls are all made correctly to the ga function.

**Comment by jasonvdzeeuw** [comment]
@justinsa We had it working with this original GA code:

(We are co-workers by the way)

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', '<GA-ACCOUNT>', 'auto');
      ga('require', 'ec');

      ga('ec:addProduct', {
          'id': 'P12345',
          'name': 'Android Warhol T-Shirt',
          'category': 'Apparel',
          'brand': 'Google',
          'variant': 'black',
          'price': '29.20',
          'quantity': 1
      });

      // Transaction level information is provided via an actionFieldObject.
      ga('ec:setAction', 'purchase', {
          'id': 'T12346',
          'affiliation': 'Google Store - Online',
          'revenue': '37.39',
          'tax': '2.85',
          'shipping': '5.34',
          'coupon': 'SUMMER2013'    // User added a coupon at checkout.
      });

      ga('send', 'pageview');     // Send transaction data with initial pageview.

    </script>

</head>
<body>

</body>
</html>
```

**Comment by justinsa** [comment]
@AVee and @jasonvdzeeuw do you need to send a pageview at the end in order to get the transaction information to be sent to GA? The service is definitely making all of the calls to the ga function, but looking at your two examples the difference appears to be in the fact that you call `ga('send', 'pageview');` at the end of the working code, but never call that at the end for the Analytics block. Have you tried adding: ```Analytics.pageView();``` to the end of the block to see if that sends the transaction data?

**Comment by jasonvdzeeuw** [comment]
@justinsa Yeah that solved it! Thanks, stupid that we didn't notice this...
You might want to add that to the documentation for people like us who didn't knew that we should add pageView() every time :+1: 

Thanks!

**Comment by Desmodue** [comment]
I'll second the documentation update, just spent most of the day trying to workout why the data wasn't being sent.

**Comment by revolunet** [comment]
Thanks for feedback ! any chance for @jasonvdzeeuw or @Desmodue to submit a pull request on the README to add the missing information where you wished have seen it ?

(sorry for frenglish)
