### ISSUE TITLE
Analytics service initialization with an explicit function call

### ISSUE THREAD

**Issue by nanocom** [revolunet/angular-google-analytics#106]
I'm currently forced to inject the Analytics service in my module.run() function without using it. This has several drawbacks : 
* the reader does not understand why an unused service is injected
* forces to add a // jshint unused:false to my run block
* can't decide wether to boot the service or not (based on a config var for example)

I'd rather have an explicit Analytics.boot(); call in my run function that wraps the service initialization and that would solve all these problems.
What do you think?

**Comment by justinsa** [comment]
I think what you want already exists.

In your app.config block you use:

```javascript
AnalyticsProvider.delayScriptTag(true)
```
**please double check the function name in the readme.**

In your run block you then inject the script as you desire.

```javascript
Analytics.createAnalyticsScriptTag();
```

**Comment by nanocom** [comment]
yes that's what I needed thanks
