### ISSUE TITLE
npm is not up to date

### ISSUE THREAD

**Issue by gitnik** [revolunet/angular-google-analytics#107]
title says it all :smile:

**Comment by justinsa** [comment]
@revolunet can you publish to NPM, please. I do not have credentials to do that and I am not exactly sure how you would give me credentials, though I would be happy to have them so I can publish in the future.

**Comment by revolunet** [comment]
looks like i can add you as an owner : https://docs.npmjs.com/cli/owner

can you give me your npm username/email please ?

**Comment by revolunet** [comment]
(published 1.1.1 on npm)
