### ISSUE TITLE
$log.debug rather than store in memory

### ISSUE THREAD

**Issue by cyrfer** [revolunet/angular-google-analytics#109]
Why store the logs in memory? I am concerned that the memory will grow quite large.

I would prefer to see $log.debug used rather than storing in memory.

Line 334 shows:
`that.log.push(args);`

**Comment by justinsa** [comment]
You have to enable the logs to be stored and it is off by default. It is intended for diagnostic usage, not production usage. You would need to specifically call: 'logAllCalls(true)' during the configuration stage to enable this.

**Comment by justinsa** [comment]
I added support for 'debug', 'info', and 'log' as supported parameters in the _log call internally. This doesn't change the implementation which is entirely meant to be for diagnostic purposes and not production operation. Closing this issue as By Design.
