### ISSUE TITLE
Page tracking not working for me

### ISSUE THREAD

**Issue by MarcAstr0** [revolunet/angular-google-analytics#110]
I have the following in my app:

```javascript

var myApp = angular.module('MyApp', [
  'ngRoute',
  'ngAnimate',
  'angular-google-analytics'
]);

myApp.run(function(Analytics) {});

myApp.config(function (AnalyticsProvider) {
  AnalyticsProvider.setAccount('UA-XXXX-X');
  AnalyticsProvider.trackPages(true);
  AnalyticsProvider.useAnalytics(false);
});
```

Which should be OK (I think) yet on Google Analytics I get that "Tracking Not Installed". When I inspect the network traffic with the Developer Tools on FF or Chrome I see that ga.js is being called. What am I doing wrong here?

Thanks.

**Comment by justinsa** [comment]
@MarcAstr0 do you want Classic (ga.js) or Universal Analytics (analytics.js)? What you have configured above is Classic analytics. If you remove the `AnalyticsProvider.useAnalytics(false);` line then it will use Universal Analytics (analytics.js). If the account is new then it is probably Universal Analytics that you want to use.

**Comment by MarcAstr0** [comment]
Apparently all I had to do was... wait. I wasn't aware that it takes some time for Google to start tracking. It's working great now. Thanks!
