### ISSUE TITLE
Add JustinSa as an NPM Owner

### ISSUE THREAD

**Issue by justinsa** [revolunet/angular-google-analytics#111]
@revolunet My NPM Username is justinsa (https://www.npmjs.com/~justinsa)

**Comment by justinsa** [comment]
@revolunet Let me know when you get a chance to do this as I just pushed version 1.1.2 for Bower and I need to update NPM. Thanks.

**Comment by revolunet** [comment]
done @justinsa, thanks for your help !

**Comment by revolunet** [comment]
btw, do you have twitter ?

**Comment by justinsa** [comment]
I do. jsaundea is my handle.
On Oct 14, 2015 12:02 AM, Julien Bouquillon <notifications@github.com> wrote:btw, do you have twitter ?

**Comment by revolunet** [comment]
cool, not sure your FitBit stats are interesting though :)

**Comment by justinsa** [comment]
They totally aren't. I need to disable that.
On Oct 14, 2015 7:01 AM, Julien Bouquillon <notifications@github.com> wrote:cool, not sure your FitBit stats are interesting though :)
