### ISSUE TITLE
Enable explicit setting of protocol

### ISSUE THREAD

**Issue by swege** [revolunet/angular-google-analytics#113]
`var scriptSource = '//www.google-analytics.com/analytics.js';` (https://github.com/revolunet/angular-google-analytics/blob/master/src/angular-google-analytics.js#L396)

When the angular application is a native mobile application (e.g. by using cordova), the protocol will be `file://` since its beeing executed inside a webview. I see no possibility to set the protocol explicitly to `https://`

This issue is kind of related with issue #31

**Comment by justinsa** [comment]
Released to Bower. Pending release to NPM.
