### ISSUE TITLE
License in bower.json

### ISSUE THREAD

**Issue by miguelCT** [revolunet/angular-google-analytics#115]
Hi,

I've been trying to create a bower-webjar with 1.1.2 version of your plugin in [www.webjars.org](http://www.webjars.org/bower), however it seems to be some problem with the license since I get this message:

>Failed! All attempts to determine a license have been exhausted. The bower.json did not contain a spec-compliant license definition and the license could not be determined by trolling through the GitHub repo. This problem will likely need to be resolved by working with the library maintainers directly. If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Determined Artifact Name: angular-google-analytics Starting Deploy

Could you please check if the sintax of the license field in bower.json is correct or maybe include a license file in the GitHub repository?

Thanks in advance.

**Comment by revolunet** [comment]
Thanks, just added a LICENSE file, hope this helps. If not, please submit a PR with requird changes

**Comment by miguelCT** [comment]
Now it works fine, thank you for adding it.
