### ISSUE TITLE
How to make AnalyticsProvider.setAccount dynamic

### ISSUE THREAD

**Issue by sukhiimangat** [revolunet/angular-google-analytics#119]
Hi, 

How can i make AnalyticsProvider.setAccount dynamic. Means getting Tracking Id from database and assigned to AnalyticsProvider.setAccount. In Angular config I cannot use $rootScope and in run I have $rootscope which has tracking id. Any idea how can i do that?

Thanks

**Comment by justinsa** [comment]
This is outside the scope of this module, but what you might want to consider is pre-loading data as part of your index page. Your index page would be server generated as you would need to generate a <script> tag that contains the data you require angular to have prior to serving the page back to the client.

**Comment by justinsa** [comment]
Closing this issue as it is not actionable for angular-google-analytics.
