### ISSUE TITLE
update a tag to 1.1.3

### ISSUE THREAD

**Issue by maruilian11** [revolunet/angular-google-analytics#126]
hi, would you please update the tags to the latest version so that we can add your lib to https://cdnjs.com **with git auto-update**.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/6261

**Comment by justinsa** [comment]
@maruilian11, what exactly do we need to do for this to work? As best I can tell there already is a 1.1.3 tag, which is how Bower also determines the version.

**Comment by justinsa** [comment]
@maruilian11 I just published the 1.1.4 release along with its tag. Perhaps this is what you required us to do in order to make the release available with cdnjs. Please close this issue if it is resolved.

**Comment by justinsa** [comment]
Completed.
