### ISSUE TITLE
Add support to Exception Tracking

### ISSUE THREAD

**Issue by camolin3** [revolunet/angular-google-analytics#130]
It would be nice if you provide a way to send exceptions to google analytics, as explained here:
https://developers.google.com/analytics/devguides/collection/analyticsjs/exceptions

**Comment by justinsa** [comment]
You can already do this by calling:

```js
Analytics.send('exception', { exDescription: '', exFatal: false });
```

I added a convenience method to accomplish this so no one has to know or write the above: `Analytics.trackException('description', false);`

PR will be out shortly.

**Comment by camolin3** [comment]
Thank you :)
Are you going to keep supporting bower?

**Comment by justinsa** [comment]
Of course. I tag every release so Bower is aware. Is there an issue with Bower?

**Comment by camolin3** [comment]
No, sorry, I've just failed at upgrading the package. It is working fine.
