### ISSUE TITLE
Can you create a Quick Start guide plz?

### ISSUE THREAD

**Issue by Leo-G** [revolunet/angular-google-analytics#135]
I like your project but I could not figure out the min options required to configure your script, I am using UI states in mine https://github.com/Leo-G/Flask-Scaffold/, but with so many options I am not sure how I can use it, a quick start would be helpful.

Thanks.

**Comment by Toxantron** [comment]
Could you specify what is missing? 

Because when I got started I found the README to be sufficient.

**Comment by quarryman** [comment]
For instance, if I look at SetDomain configuration, how do i know if it's mandatory or not and what is the minimum set of config options that must be set?

**Comment by Toxantron** [comment]
I only set tracking id - like you would do with the normal tag. Was enough to start tracking. Everything else is basically optional. For example I suppose google already linked your Domain with the tracking id.

**Comment by vrghost242** [comment]
I was hoping to kind of tag along on this thread (because it seems overkill to open a new one). 

The readme file seems good, but tricky to get the minimum up. Maybe just instructions how to set the ID (think I figured that out) then testing it, as analytics is a bit of a closed box, and it can take it a while (think they say up to an hour) to start accepting entries on an id.

**Comment by Toxantron** [comment]
I do agree there. Maybe we can split the README into seperate files or just restructure it. It seems to have grown over time and now might be a little confusing regarding its order. For example it is confusing that a mandatory instruction like `app.run(function(Analytics) { })` is hidden somewhere in the  middle.

**Comment by vrghost242** [comment]
That would be amazing. So the minimal (lets start with minimal with automated page view tracking) would be?

````
var app = angular.module('app', ['angular-google-analytics' ])
.config(function (AnalyticsProvider) {
        // Add configuration code as desired - see below
        AnalyticsProvider.setAccount({
            tracker: 'UA-75034784-2',
        });
    })
    .run(function(Analytics) {})
```

And then every call should be logged, or would I need to add something to the controller as well?

**Comment by vrghost242** [comment]
Certain you guys will do an amazing job. But in the meanwhile, if anyone wonders. To see if it is working, open the java console in Chrome (or any other browser) open the network tab, reload the page. You should see a connection to google-analytics.com/collect that reads something like

````
http://www.google-analytics.com/collect?v=1&_v=j41&a=1318033733&t=pageview&_s=1&dl=http%3A%2F%2F127.0.0.1%2F&dp=%2F&ul=en-us&de=UTF-8&dt=webpage&sd=24-bit&sr=1440x900&vp=1039x668&je=0&fl=21.0%20r0&_u=AACAAEABI~&jid=&cid=352432347.1442442427669&tid=UA-XXXXXXXXX-2&z=1142080982 
````

**Comment by Toxantron** [comment]
You can even do less:
```
var app = angular.module('app', ['angular-google-analytics' ])
  .config(function (AnalyticsProvider) {
        // Add configuration code as desired - see below
        AnalyticsProvider.setAccount('UA-YourId-0');
    })
    .run(function(Analytics) {})
```

**Comment by vrghost242** [comment]
How do I create the session for the user session. 
I.E. When it first loads,  I want it to tell Google analytics,  we got a user session,  and when the user leaves I want to close it. 

Reason for asking is that the above code gives me page tracking,  but it does not show up in live view, which would be useful:)

**Comment by Toxantron** [comment]
Well, I don't know why but I did the same and I get information about currently active users, time on page, etc.

**Comment by vrghost242** [comment]
OK, somehow I managed to break it (I am pretty good at breaking things, like a pro) by using the exact code above. 

Then I unbroke it, have no clue how, but turning on the following options. 

           displayFeatures: true,
            enhancedLinkAttribution: true,
            trackPages: true,
            trackEvent: true,
            trackEcommerce: true

Works now and thank you very much for the help mister Toxatron:)

**Comment by Toxantron** [comment]
Considering the fact I just recently started using it myself I am happy I could help.;)

**Comment by damiangreen** [comment]
What exactly is 'Analytics ' @Toxantron . I have strict-di enabled in my app and having this in run causes the strictness to fail as it's not injected anywhere?

**Comment by Toxantron** [comment]
'Analytics' is the module itself. Simly put the entire point of this project is to provider the 'Analytics' module. Did you include the angular-google-analytcs.js in your project?

**Comment by damiangreen** [comment]
Ah, i can keep strict-di enabled if i have something like this 

```
.run(['$rootScope', '$translate', 'Analytics', 
function ($rootScope, $translate, Analytics) {
..yada
}
```

Although resharper is telling me to remove the Analytics param in the function call as its unused. Which i can live with

**Comment by Toxantron** [comment]
Oh, do you use any minifier? Minified code requires the array with named parametes because the minifier renames the variables.

**Comment by damiangreen** [comment]
@Toxantron , yep, you're right, that's the reason i use the strict-di attribute.

**Comment by Toxantron** [comment]
All good then?

**Comment by monk8800** [comment]
I think the README file should differently be updated with @Toxantron sample code as the bare minimum required to setup the script. I went a few rounds trying to make sense of the huge amount of options available. Still waiting for the GA tracking to take effect, was not aware that it could take a few hours to get GA to display tracking data.

**Comment by revolunet** [comment]
anyone willing to create a "quick start" section in the README ?

**Comment by Toxantron** [comment]
Sure, but won't have time for it till next week.
