### ISSUE TITLE
Is it possible to setAccount after module config?

### ISSUE THREAD

**Issue by someone235** [revolunet/angular-google-analytics#140]
in .run or inside a controller?

**Comment by justinsa** [comment]
Not at present. There is a lot of logic that goes into defining an account properly and all of that work is done during script injection, which can only ever happen once.

This could be changed.

What exactly is your use case requiring this?

**Comment by someone235** [comment]
I have a view where I send to the server a parameter from $stateParams, and then get in the response the relevant tracker id.

**Comment by justinsa** [comment]
See #146 for an example of what you could do with the existing logic.
