### ISSUE TITLE
Package for nuget

### ISSUE THREAD

**Issue by Toxantron** [revolunet/angular-google-analytics#148]
Working with ASP.NET (Core) I think the project could reach more users when it is available on nuget as well. So far grunt and npm only cover node and php projects.

**Comment by justinsa** [comment]
I had no idea that PHP projects were heavily using NPM. I used to be a .NET developer (10 years). I haven't programmed in VS for a while now, but releasing for nuget was pretty straightforward as I recall. Good idea. Thanks, @Toxantron.

**Comment by Toxantron** [comment]
Well I don't think *heavily* but getting a js package via npm is an option. I think the php choice is bower which wie could also add support for.

**Comment by justinsa** [comment]
We already release to Bower.
On Apr 9, 2016 23:27, Thomas Fuchs <notifications@github.com> wrote:Well I don't think heavily but getting a js package via npm is an option. I think the php choice is bower which wie could also add support for.

**Comment by Toxantron** [comment]
I know. Didn't have coffee and kinda forgot. ;-)

**Comment by revolunet** [comment]
I think if you need "nuget" then you can release it there on your own ?

**Comment by Toxantron** [comment]
Sure I can. I thought you might be interested of adding it to the project
in general. Since 'nuget' differentiates between author and publisher I can
use my account and attribute it to you.

Should I include 'nuget' config via PR later?

**Comment by revolunet** [comment]
sounds good ! yes add the nuget config with a PR please

thank you
