### ISSUE TITLE
Type Error, not a function

### ISSUE THREAD

**Issue by dennisbrandt** [revolunet/angular-google-analytics#159]
In my config block I try to call 

```
AnalyticsProvider
       .logAllCalls(true)
       .startOffline(true)
       .useEcommerce(true, true);
```

built.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module layerCakeApp due to:
TypeError: g.logAllCalls(...).startOffline(...).useEcommerce is not a function

Everything is included and declared as a dependency, while in my config block I inject AnalyticsProvider. This is probably something stupid, but any ideas on where I am going wrong? 

Cheers!

**Comment by justinsa** [comment]
`useECommerce` -> There is a capital `C` in there.

**Comment by Toxantron** [comment]
You seem to be using minified js. In this case you can not use
`function(AnalyticsProvider)` since the minifer strips away the name.
Rather use `['AnalyticsProvider', function(AnalyticsProvider)]` to make
sure the name is preserved.

**Comment by dennisbrandt** [comment]
Hey, I do do that, the Capital C in ecommerce seems to be it. I suppose the docs need updating?

**Comment by justinsa** [comment]
Fixed the documentation.

**Comment by dennisbrandt** [comment]
Awesome, thanks guys!
