### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by cyrfer** [revolunet/angular-google-analytics#163]
It would be helpful to have a NPM package.

As I understand it, we must use bower to install this. I am already using NPM for many other dependencies, including angular. Installing this causes bower_components to have a shadow copy of angular that I worry will get out of sync with node_modules.

**Comment by Toxantron** [comment]
Unless I misunderstood your question there is a NPM module right [here](https://www.npmjs.com/package/angular-google-analytics). It is one of the badges on top of the **README** file.

**Comment by Toxantron** [comment]
I just tried `$ npm i angular-google-analytics` and it works like a charm.

**Comment by cyrfer** [comment]
@Toxantron - my apologies. I did not know what 'badges' were. My eyes jumped to the `bower install` instructions. I am used to other projects stating the NPM instructions also. I will update my package references now.

Perhaps you could state the NPM instructions next to the Bower instructions.

Thank you for pointing out the solution, and for maintaining a great project.

**Comment by Toxantron** [comment]
No apology needed. I am glad I could help. 

I will create a PR to include install commands for NPM and Nuget, let's see what @revolunet  and @justinsa  think about it.

**Comment by Toxantron** [comment]
@justinsa I think this can be closed, unless @cyrfer has any objections?
