### ISSUE TITLE
Have you DefinitelyType? 

### ISSUE THREAD

**Issue by cawa-93** [revolunet/angular-google-analytics#166]
This needs for typescript code

**Comment by Toxantron** [comment]
Since it is was written in pure Javascript there are no TypeMappings for TypeScript. If I find the time to continue work on version 2.0 for Angular 2.0 it will be written in TypeScript. Till then I don't think we have what you need.

**Comment by cawa-93** [comment]
Очень жаль

**Comment by cawa-93** [comment]
I found this. If you have time, it would be good for you to check and complement it.

[DefinitelyTyped/angular-google-analytics](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/cc3d223a946f661eff871787edeb0fcb8f0db156/angular-google-analytics)

**Comment by Toxantron** [comment]
@cawa-93 thank you for the hint. 

I extended the methods I found in the commits since 1.1.0 in DefinitelyTyped/DefinitelyTyped#13958

I can not guarantee that it now covers all methods, I just assumed that @cyrilschumacher intial work was valid till 1.1.0
