### ISSUE TITLE
Can anyone share examples ?

### ISSUE THREAD

**Issue by 29er** [revolunet/angular-google-analytics#174]
Hi I'm just looking for someone to share some working examples of tracking events/ page/state changes etc.  I was hoping to find some 'real world' example is this repo, but no luck. 
Thanks ! 
Our app is ng 1.5 +

**Comment by cawa-93** [comment]
1. https://github.com/cawa-93/vknotice/blob/develop/src/HeaderApp/Header.tpl#L28
2. https://github.com/cawa-93/vknotice/blob/develop/src/HeaderApp/js/HeaderCtrl.ts#L44

**Comment by Toxantron** [comment]
In my ScrumPoker application I track button clicks.

[In Template](https://github.com/Toxantron/scrumonline/blob/master/src/templates/default_source.html#L6)
[In JavaScript](https://github.com/Toxantron/scrumonline/blob/master/src/templates/default_source.html#L6)

**Comment by 29er** [comment]
Thanks very much ! great info
