### ISSUE TITLE
Error: [$injector:strictdi] function(AnalyticsProvider) is not using explicit annotation and cannot be invoked in strict mode

### ISSUE THREAD

**Issue by lrkwz** [revolunet/angular-google-analytics#180]
I have an angularjs application where app.module.js is:

```
(function() {
    'use strict';

    angular
        .module('myApp', [
           // ...
            'angular-google-analytics'
        ])
        .config(function (AnalyticsProvider) {
        	   // Add configuration code as desired
        	   AnalyticsProvider.setAccount('UU-XXXXXXX-X');  //UU-XXXXXXX-X should be your tracking code
        	})
        .run(run);

    run.$inject = ['stateHandler', 'translationHandler', 'Analytics'];

    function run(stateHandler, translationHandler, Analytics) {
        stateHandler.initialize();
        translationHandler.initialize();        
    }
})();
```

I cannot understand how to invoke ```.config()``` correctlry

**Comment by justinsa** [comment]
@lrkwz Please read: https://docs.angularjs.org/error/$injector/strictdi

This issue is not with angular-google-analytics library but how you have written the code.

You either need to use the annotated method call or the $inject function to declare dependencies.

As in:

```javascript
config.$inject('AnalyticsProvider');
```

or

```javascript
.config(['AnalyticsProvider', function (AnalyticsProvider) { ... }]);
```

**Comment by lrkwz** [comment]
Ok thank you, I've fixed the configuration and posted my question here http://stackoverflow.com/questions/40612321/start-tracking-angular-google-analytics sorry for bothering here.

**Comment by justinsa** [comment]
@lrkwz Posting your question on StackOverflow probably won't get you a response since you are asking a question about how angular-google-analytics configuration and setup works.

Have you thoroughly gone through the README and tried following the quick start?

**Comment by lrkwz** [comment]
yes ... as you can see I did not understand (probabily because I'm an
angularjs newbie), but I'm not the only one
http://stackoverflow.com/questions/40192085/angular-google-analytics-integration

*=> Luca <http://stackexchange.com/users/239746>*



2016-11-15 16:49 GMT+01:00 Justin Saunders <notifications@github.com>:
