### ISSUE TITLE
Argument 'fn' is not a function, got string

### ISSUE THREAD

**Issue by harshamadala** [revolunet/angular-google-analytics#181]
Followed these stips but getting error "Argument 'fn' is not a function, got string"
1. bower install angular-google-analytics
2. <script src="bower_components/angular-google-analytics/dist/angular-google-analytics.js"></script>
3. var myApp = angular.module('myModule', ['angular-google-analytics']);
4. myApp.config(function (AnalyticsProvider) {
   // Add configuration code as desired
   AnalyticsProvider.setAccount('UU-XXXXXXX-X');  //UU-XXXXXXX-X should be your tracking code
}).run(['Analytics'], function(Analytics) { });

I am getting error after doing 4th step. Am i doing anything wrong? Can anyone please help?  Is there any version requirement for angular js?

**Comment by lyvyu** [comment]
What version of angular are you using ?

**Comment by revolunet** [comment]
looks like `myApp.config(function (AnalyticsProvider) {` is not minifier-friendly ? 

shouldnt you use `myApp.config(['AnalyticsProvider', function (AnalyticsProvider) {` ?

**Comment by revolunet** [comment]
just realized this is written the same way on the README. can someone confirm the correct syntax for the `config`  block ?

**Comment by Toxantron** [comment]
@revolunet from the top of my head I would agree. I see no reason why `config()` would behave differently when minified. @harshamadala could you try to copy the method syntax from `run()`?

**Comment by justinsa** [comment]
The problem is the 'run' method is configured incorrectly.

```javascript
}).run(['Analytics'], function(Analytics) { });
```

That is not how DI declarations work in Angular. This should be:

```javascript
}).run(['Analytics', function(Analytics) { }]);
```

Array declaration DI requires the function handler be the last item in the array. Angular was telling you that it found a string instead of a function as the last item in your array.

**Comment by revolunet** [comment]
good catch @justinsa  👀 

should we also fix the injection for AnalyticsProvider in the README ?

**Comment by harshamadala** [comment]
Thanks everyone for quick replies
