### ISSUE TITLE
Example syntax error 

### ISSUE THREAD

**Issue by nmarcetic** [revolunet/angular-google-analytics#182]
In README file Installation and Quick Start section you have a syntax error which brake the code
https://github.com/revolunet/angular-google-analytics#3--set-your-google-analytics-account-and-start-tracking
Should be .run(['Analytics', function(Analytics) { }]);   -- The ['Analytics'], function is not valid

**Comment by revolunet** [comment]
thanks, i just sent a patch here https://github.com/revolunet/angular-google-analytics/pull/183

**Comment by nmarcetic** [comment]
Thank you! I am closing this one.
