### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by Toxantron** [revolunet/angular-google-analytics#184]
1.1.8 was released a couple of days ago, but only bower was updated. We should update npm and nuget as well.

I will update nuget and create a PR.

**Comment by Toxantron** [comment]
I updated [the nuget package](https://www.nuget.org/packages/angular-google-analytics/1.1.8) but there will be no PR since you @justinsa prepared the `.nuspec` already.

@justinsa can you update NPM and close this, or does @revolunet own the account.

**Comment by justinsa** [comment]
Published 1.1.8 to NPM. It may take a bit for NPM to display the update.
