### ISSUE TITLE
Analytics.registerScriptTags and Analytics.registerTrackers are undefined

### ISSUE THREAD

**Issue by igorjacauna** [revolunet/angular-google-analytics#191]
I'm using version 1.1.8 and when use `AnalyticsProvider.delayScriptTag(true);` and after try call 

```
Analytics.registerScriptTags();
Analytics.registerTrackers();
```

They are undefined.

I guess the files into `dist `directory are outdated. I searched by `registerScriptTags `and `registerScriptTags` in `angular-google-analytics.js` and `angular-google-analytics.min.js` files. No success.

**Comment by justinsa** [comment]
Hey @igorjacauna - the files in the `dist` folder are very much out-of-date. I will look at updating those with the grunt build script. Most people use `npm`, `bower`, or `nuget`. You can also use the `index.js` file in the root folder for the meantime (and just rename it).

**Comment by igorjacauna** [comment]
Hi! I use bower, and in the file `bower.json` the main reference is to `dist` folder. So, when I builded my project, it imported from out-of-date `dist` folder.

**Comment by justinsa** [comment]
Ah! Thanks for letting us know. We will get this fixed ASAP.

**Comment by justinsa** [comment]
This is now updated with a 1.1.9 release tag.
