### ISSUE TITLE
GA not working with JXBrowser

### ISSUE THREAD

**Issue by ikabar-tracxpoint** [revolunet/angular-google-analytics#197]
I'm using jxbrowser for a desktop application. JXBrowser is based on Chromium version 51.
 
I'm trying to use Google Analytics but there is some strange behaviour.
When running the code via Chrome the analytics are sent as expected (and visible in the dashboard). 
But when running the same code in the JXBrowser no data is shown in the dashboard.
 
I used a sniffer and I noticed that the request to google analytics are not sent from the JXBrowser (The application connects to external servers without a problem).
 
Does anyone know what could be the cause for that issue?

**Comment by justinsa** [comment]
It sounds like your issue is with JXBrowser and the Google Analytics script directly. It would be better to ask your question on the JXBrowser or Google Analytics forums as someone may have come across your problem there.
