### ISSUE TITLE
`$window.ga has initialized` event

### ISSUE THREAD

**Issue by machulav** [revolunet/angular-google-analytics#198]
I need to know when the `$window.ga` will be initialized by the `angular-google-analytics` wrapper and then run my custom script which should let me know whether AdBlocker works on the page and block `$window.ga`:

```
if (!this._globalGA || !this._globalGA.create || !this._globalGA.loaded) {
      this._loggerService.log('AdBlocker detected - Case 2: Google Analytics disabled');
}
```

Do you have such event in the plugin? 
How can I know that `$window.ga` has initialized already?

Thank you!

**Comment by machulav** [comment]
@revolunet @deltaepsilon @justinsa do you have an idea how to do this?

**Comment by justinsa** [comment]
@machulav This library doesn't know about the state of $window.ga beyond the script being injected on the page. All commands are run through the standard interface with the GA function call. That function simply pushes to an array and the GA script does its business with the calls this library makes to the `ga` function.

You might want to read through the GA documentation to figure out if the ga object exposes any events or state information that you can connect to.

**Comment by machulav** [comment]
@justinsa thank you for the answer!
