### ISSUE TITLE
enhanced eCommerce data is not being send to GA

### ISSUE THREAD

**Issue by Desmodue** [revolunet/angular-google-analytics#206]
Analytics.trackCheckout does not send data to ga. Looking through closed issues, this issue enhanced eCommerce data is not being send to GA #201 zkovalenko is exactly what I am seeing.
Unfortunately it was closed with no reply...

What am I doing incorrectly ?
All the cart tracking works, just that ga always shows the checkout as being abandoned.
Google analytics debug shows the items and setAction checkout but does not appear to send it.
I'm at a bit of a loss as to where to go from here.
cid & tid are the same  throughout the session....

**Comment by Desmodue** [comment]
**UPDATE**
Not obvious to me in the docs but issuing a pageView directly after sends the data to GA.

**Comment by revolunet** [comment]
Thanks for reporting
