### ISSUE TITLE
outbound transport calls not supported

### ISSUE THREAD

**Issue by lastlink** [revolunet/angular-google-analytics#210]
Google analytics supports outbound calls. Typically these are done w/ a parameter of transport: 'beacon' and a parameter that reroutes after the analytics tracking event has been sent. I've setup  2 pull requests to update this.
https://github.com/revolunet/angular-google-analytics/pull/209
https://github.com/revolunet/angular-google-analytics/pull/208

**Comment by justinsa** [comment]
I've closed PR #209 as this is already supported and provided the following comment:

Actually, on further consideration this change is unnecessary as the desired functionality is already available via the "custom" attribute. In the event call you can provide the required fields and they will be appended to the options object sent to GA. e.g.,

```
{
  transport: 'beacon',
  hitCallback: function () { ... }
}
```

There is no need to modify the library for this functionality.

Additionally, I will update the README to example this as what was pulled in via PR #208 is incorrect.
