### ISSUE TITLE
How to disable logging to the console?

### ISSUE THREAD

**Issue by CheungJ** [revolunet/angular-google-analytics#218]
For protractor tests, I have disabled analytics via `disableAnalytics(true)`.
However, it's writing the following message to the console:

```cmd
[1128/123839.712:INFO:CONSOLE(44240)] "Analytics disabled: ..."
```

Protractor is seeing the message and outputting it to the terminal.

Is there a way to completely prevent all console logs?

**Comment by justinsa** [comment]
1. You could provide the service a stub $log service and just noop all calls to it.
2. You could use offline mode instead of disableAnalytics. Offline mode doesn't load the GA scripts and just logs all calls to an internal queue.

**Comment by CheungJ** [comment]
Thanks for the speedy response!
You second option worked: `AnalyticsProvider.startOffline(true);`

Thank you!
