### ISSUE TITLE
input tracking

### ISSUE THREAD

**Issue by yakupad** [revolunet/angular-google-analytics#224]
Hello!
I want to watch the input. How can I use this library for this?

![ekran resmi 2018-03-21 15 52 48](https://user-images.githubusercontent.com/12917333/37710844-f7bea194-2d1f-11e8-8f67-861d4eacb7bb.png)

**Comment by megamanhxh** [comment]
Have a look into this:
https://github.com/revolunet/angular-google-analytics#event-tracking

**Comment by yakupad** [comment]
Thanks @megamanhxh
