### ISSUE TITLE
GA Analytics does not working in iframe

### ISSUE THREAD

**Issue by avtaniket** [revolunet/angular-google-analytics#233]
I have website "https://www.customer-name.our-website.com" which we adds in customers websites ""https://www.customer-website.com"" as iframe so that its easy integration for them.

GA analytics of our site isn't working as cookie are not set, not sure why? we have set cookie settings as "secure"

Note : Cross domain Cookies doesn't works in Mac - Safari, Windows - Chrome and Andriod - chrome only other browsers working

Doesn't cross domain cookie works??

**Comment by jsandeepm** [comment]
Hi 

> I have website "https://www.customer-name.our-website.com" which we adds in customers websites ""https://www.customer-website.com"" as iframe so that its easy integration for them.
> 
> GA analytics of our site isn't working as cookie are not set, not sure why? we have set cookie settings as "secure"
> 
> Note : Cross domain Cookies doesn't works in Mac - Safari, Windows - Chrome and Andriod - chrome only other browsers working
> 
> Doesn't cross domain cookie works??

Hi
You can use the below settings. I tried it and its working.

fields: {
                    'cookieFlags': 'SameSite=None; Secure'
  }

![image](https://user-images.githubusercontent.com/9821180/123918424-7f155a80-d9a1-11eb-9317-8a09beec8110.png)

**Comment by avtaniket** [comment]
Yes right, `https://www.simoahava.com/analytics/cookieflags-field-google-analytics/`

Currently using  `AnalyticsProvider.setCookieConfig({'cookieFlags': 'SameSite=None; Secure'});`
