### ISSUE TITLE
Support for custom variables/dimensions?

### ISSUE THREAD

**Issue by kyleBeikirch** [revolunet/angular-google-analytics#28]
Is there and will there be support for custom variables/dimensions ?

https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs#custom-vars

**Comment by IdoHakimi** [comment]
see: https://github.com/revolunet/angular-google-analytics/issues/65

**Comment by armyofda12mnkeys** [comment]
Should this be closed? i see supposed support for this based on the functions seen in the documentation below:
```
// or create a new pageview event with optional page title, custom dimension and metric// (analytics.js only)
Analytics.trackPage('/video/detail/XXX', 'Video XXX', {dimension15: 'My Custom Dimension', metric18: 8000});
// populate a custom dimension
Analytics.set('dimension1', 'Paid');
```

However the set() nor the custom trackPage() funcs don't work for me.
Can anyone confirm if custom dimensions actually are added?

**Comment by armyofda12mnkeys** [comment]
trackPage works actually. I figured out i was sending the dimension name in that object and not the 'dimension#'. Maybe this ticket can be closed?

**Comment by stramel** [comment]
@kyleBeikirch @revolunet Am I missing something? As the documentation (and @armyofda12mnkeys) states:

```js
// populate a custom dimension
Analytics.set('dimension1', 'Paid');
```

I am using this method to set the custom dimensions in my application without any issues. I have also used the alternate method of: 

```js
// or create a new pageview event with optional page title, custom dimension and metric// (analytics.js only)
Analytics.trackPage('/video/detail/XXX', 'Video XXX', {dimension15: 'My Custom Dimension', metric18: 8000});
```

Please elaborate on the issue.

**Comment by justinsa** [comment]
Closing as this has been added and confirmed working for what was originally requested.
