### ISSUE TITLE
Support for hybrid mobile app

### ISSUE THREAD

**Issue by reyazucar** [revolunet/angular-google-analytics#31]
Hi, 
could you expose the property checkProtocolTask in order to add support for hybrid mobile apps?
ga(‘set’, ‘checkProtocolTask’, null); 
For hybrid mobile app is required disable the check protocol task, in order to suppor file:// protocol

In this post (http://www.blastam.com/blog/index.php/2013/07/ga-universal-analytics-phonegap-mobile-apps) you can see in more detail about this

thanks & regards

**Comment by petermetz** [comment]
I haven't tried this, but it seems like it could work:
Inject the Analytics service in your ```run``` block and call

    Analytics.set('checkProtocolTask', null);

It might be too late to do this kind of configuration in the run block in your case.
