### ISSUE TITLE
Publish it to npm as well ...

### ISSUE THREAD

**Issue by binarykitchen** [revolunet/angular-google-analytics#36]
... so that I can include it via browserify instead of bower.

Thanks!

**Comment by charwking** [comment]
It looks like there hasn't been an npm release since version 0.0.5. I'd love to use the new `trackUrlParams` feature. Any plans to continue publishing to npm?

Thanks!

**Comment by revolunet** [comment]
just published npm update. hope its ok. thanks

**Comment by binarykitchen** [comment]
hmmm, it's breaking my app - why do you have bower in your scripts?

```
    "postinstall": "node ./node_modules/bower/bin/bower install",
    "postupdate": "node ./node_modules/bower/bin/bower update",
```

Please remove this. Or figure out something else.

**Comment by revolunet** [comment]
removed

**Comment by binarykitchen** [comment]
good - please npm publish that again
