### ISSUE TITLE
Multiple accountIds and crossDomainLinker

### ISSUE THREAD

**Issue by zaggino** [revolunet/angular-google-analytics#50]
From this code I can see that it's not possible to use an array of `accountId`s and `crossDomainLinker` at the same time. Is there a reason for that? I'm not very familiar with `analytics.js` and I haven't seen a mention of this anywhere in the docs.

Src:
https://github.com/revolunet/angular-google-analytics/blob/3055c1a1724f6037960a3c2143345609cf8345a0/src/angular-google-analytics.js#L174-L186

**Comment by justinsa** [comment]
@zaggino It is possible to define crossDomainLinker for multiple accounts but the definitions need to be set as part of each account object. With the latest update the documentation should provide an example of this value being provided.
