### ISSUE TITLE
Event tracking with Multiple accounts

### ISSUE THREAD

**Issue by flumonion** [revolunet/angular-google-analytics#52]
Is there a reason you only track page views for multiple accounts, why not events and others?

e.g. line 316 would become:
```
_analyticsJs(function () {
          if (angular.isArray(accountId)) {
            accountId.forEach(function (trackerObj) {
              $window.ga(trackerObj.name + '.send', 'event', category, action, label, value);
            });
          } else {
            $window.ga('send', 'event', category, action, label, value);
          }
          that._log('event', args);
        });
```

**Comment by justinsa** [comment]
@flumonion - page views and events support multiple trackers but the ecommerce and enhanced ecommerce commands do not yet support multiple trackers.

**Comment by jasonvdzeeuw** [comment]
@justinsa is there a reason why you don't support the E-commerce tracking with multiple trackers?
because I really need it now for an application.

I use the page views and events tracking, and push it to two trackers. Now I want to register the e-commerce the same way.

**Comment by justinsa** [comment]
@jasonvdzeeuw all operations now support multiple trackers, e-commerce and enhanced e-commerce included. See the documentation on the homepage for usage information. Version 1.1.0 has been published to Bower but has not been published to NPM as that is waiting on @revolunet.
