### ISSUE TITLE
Add helper directives for simpler use

### ISSUE THREAD

**Issue by tsov** [revolunet/angular-google-analytics#58]
A good idea might be to provide some helper directives to simplify the use even more.

e.g.
```html
<button ng-repeat="button in buttons" ga-track-event="button.ga"></button>
```

where button.ga might look something like `{category: 'video', action: 'play', label: 'video.mp4'}` or maybe even `['video', 'play', 'video.mp4']`. Meaning you don't even need to write code in your controllers for some simple actions.

Working on a sample working version on `tsov/angular-google-analytics`, once ready I will propose a PR, but what are general thoughts on this one?

**Comment by tsov** [comment]
https://github.com/revolunet/angular-google-analytics/pull/59

**Comment by deltaepsilon** [comment]
Done.
