### ISSUE TITLE
ga-track-event directive should have optional "if" statement

### ISSUE THREAD

**Issue by jonespen** [revolunet/angular-google-analytics#64]
Something like [angulartics](https://github.com/luisfarzati/angulartics#declarative-tracking), very handy.

**Comment by khashayar** [comment]
What's the problem with using ng-if?

**Comment by jonespen** [comment]
That would hide the whole element if falsy, this is for conditional event tracking. I can submit a pull request.

**Comment by justinsa** [comment]
Closing as issue is resolved.
