### ISSUE TITLE
Adding Custom Dimensions and Metrics

### ISSUE THREAD

**Issue by IdoHakimi** [revolunet/angular-google-analytics#65]
In the current implementation it is not possible to add custom Dimensions and Metrics in products.
For Example:
ga('ec:addProduct', {               // Provide product details in an productFieldObject.
  'id': 'P12345',                   // Product ID (string).
  'name': 'Powerup',                // Product name (string).
  'category': 'Extras',             // Product category (string).
  'variant': 'red',                 // Product variant (string).
  'price': '10.00',                 // Product price (currency).
  'quantity': 2,                    // Product quantity (number).
  'dimension4': 'strong',           // Product-scoped custom dimension (string).
  'metric2': 5                      // Product-scoped custom metric (integer).
});
 
see more at: https://developers.google.com/analytics/devguides/platform/customdimsmets.
 
My suggestion would be to add a _addProductObject(obj) and _removeProductObject(obj) which will send the object in the same format as above.

**Comment by stramel** [comment]
Maybe this could do something like the `trackPage` where the custom options can be passed as an object?

**Comment by justinsa** [comment]
@IdoHakimi A fix for this is out for review.
