### ISSUE TITLE
Feature request: Expanded experiments support

### ISSUE THREAD

**Issue by egeland** [revolunet/angular-google-analytics#66]
Hi,

As a companion to Analytics, I am using `angular-google-experiments` to set up experiment variations - and was wondering if you could incorporate this functionality into the Analytics module for simplicity?
Would be good to have it all in one place..
The fork at https://github.com/eaguerralde/angular-google-experiments/blob/master/googleExperiments.js seems to have simplified the loading of the experiments js by using `angularLoad`. Maybe a better way than in the origin, where a timeout is used?

Thanks for creating this Analytics module! I use it in all my angular webapps!

**Comment by revolunet** [comment]
Hey :)
Are you sure this is the lib you use ? you mention http://luisfarzati.github.io/angulartics in your README but its another beast.

**Comment by egeland** [comment]
Yes, I know that that `experiments` module mentions `angulartics`, but I use your module for Analytics, as it is more focused on GA. :)

**Comment by justinsa** [comment]
@egeland - what exactly is needed to be done here? The support for loading the experiment script with the experimentId is already implemented in this script. What else is needed for this feature request?

**Comment by egeland** [comment]
Hmm... almost six months ago... can't really remember what my issue was...
