### ISSUE TITLE
possible to start new session via sessionControl?

### ISSUE THREAD

**Issue by armyofda12mnkeys** [revolunet/angular-google-analytics#67]
Just curious GA has the ability to start a new session manually via the sessionControl option:

https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#sessionControl

```
ga('send', 'pageview', {'sessionControl': 'start'});
```

How can this option be used in angular-google-analytics? 
Not sure if there is a way to pass options like that to pageView manually [think i only saw example of dimension and metric data being passed with a manually pageView in the documentation]

Thanks,
Ari

**Comment by revolunet** [comment]
Looks like this is possible : https://github.com/revolunet/angular-google-analytics/blob/master/src/angular-google-analytics.js#L346

did you try something like this ?
```js
Analytics.trackPage(null,null, {sessionControl: 'start'});
```

**Comment by armyofda12mnkeys** [comment]
that looks like its working, i do see sessionControl shortened to 'sc' and passed along to ga.
A side-note question... I thought that 3rd param was for 'Dimensions' since thats the main example I see on the page:
 Analytics.trackPage('/video/detail/XXX', 'Video XXX', {dimension15: 'My Custom Dimension', metric18: 8000});

Yet if i combine a dimension of mine with sessionControl in that object, I don't see those custom dimension params passed along in the request (but I still see 'sc')?
Shouldn't they be passed along? is this a bug?

```
Analytics.trackPage('/questionnaire/'+ $scope.currentquestion.id, 'Question'+ $scope.currentquestion.id, { questionnaire_name: $scope.questionnaire.title,  question_id: $scope.currentquestion.id, sessionControl: 'end'} ); //questionnaire_name= session dimension var, question_id = Hit dimension var since it changes question to question
```

**Comment by armyofda12mnkeys** [comment]
I figured out Dimensions work :). I was passing the actual dimension names like 'questionnaire_name' when it should be something like 'dimension1' (whatever the # is in the GA Dimensions Admin screen)
