### ISSUE TITLE
Use analytics.js by default

### ISSUE THREAD

**Issue by nanocom** [revolunet/angular-google-analytics#68]
It took me some time to understand that I had to call AnalyticsProvider.useAnalytics(true) to make it work. I think it would be easier if analytics was used by default.

**Comment by stramel** [comment]
:+1:

**Comment by justinsa** [comment]
This is a good time to make it universal analytics by default. The next release is going to break backwards compatibility for a number of universal analytics behaviors so we might as well go all the way with moving towards the future.
