### ISSUE TITLE
Dynamically set the UA Account as the route changes?

### ISSUE THREAD

**Issue by sonicparke** [revolunet/angular-google-analytics#71]
I'm using ui-router and need to change the UA account based on the route. Is there a mechanism to do this currently?

**Comment by justinsa** [comment]
@sonicparke This isn't a feature in this service and I can't think of a way you would be able to do such a thing with the existing implementation. While the service does support multiple accounts they are all equally used in calls and you cannot be selective of when they are used based on some kind of provided closure. Though such a feature sounds reasonable to support and should be fairly light to incorporate.
