### ISSUE TITLE
Does E-commerce work properly?

### ISSUE THREAD

**Issue by Karpo72** [revolunet/angular-google-analytics#80]
First I tried to set up E-Commerce like in the example on Github (usinig UniversalAnalytics).
I use multiple tracker -> two different Analytics ID's. 

AnalyticsProvider.useECommerce(true, true);
This causes an warning:
Enhanced ecommerce plugin is enabled. Only one plugin(ecommerce/ec) can be used at a time. 

After that I tried to set it up like this to try:
AnalyticsProvider.useECommerce(false, true);
This causes also a warning:
'ecommerce not set. Use AnalyticsProvider.setECommerce(true, false);'

After that I tried to set it up like this to try:
AnalyticsProvider.useECommerce(true, false);

Now I get no warning. But from the Network Tab in Chrome Dev Tools I see that no data is send by analytics. Within analytics I get no Transactions tracked. How to use E-commerce Tracking and the advanced e-commerce plugin?

Might it it be that the support for multiple trackers is missing on e-commerce? I don't see a loop for each trackker inside the e-commerce functions.

**Comment by justinsa** [comment]
I am going to look into this and see what needs to be fixed.

**Comment by Karpo72** [comment]
thanks a lot ;-)

**Comment by Karpo72** [comment]
bower ENORESTARGET  No tag found that was able to satisfy 0.0.18  ;-)

**Comment by revolunet** [comment]
github tag just released for bower in addition to the NPM release

**Comment by Karpo72** [comment]
Might it be that there are still problems on e-commerce using multiple trackers? I took a look into the code, but I couldn't see how multiple trackers are implemented or is the function called multiplke times? I still don't receive e-commerce data

```javascript

 this._addTrans = function (transactionId, affiliation, total, tax, shipping, city, state, country, currency) {
          var that = this, args = arguments;
          _gaJs(function () {
            $window._gaq.push(['_addTrans', transactionId, affiliation, total, tax, shipping, city, state, country]);
            that._log('_addTrans', args);
          });
          _analyticsJs(function () {
            if (that._ecommerceEnabled()) {
              $window.ga('ecommerce:addTransaction', {
                id: transactionId,
                affiliation: affiliation,
                revenue: total,
                tax: tax,
                shipping: shipping,
                currency: currency || 'USD'
              });
              that._log('ecommerce:addTransaction', args);
            }
          });
        };
```
```javascript
this._addItem = function (transactionId, sku, name, category, price, quantity) {
          var that = this, args = arguments;
          _gaJs(function () {
            $window._gaq.push(['_addItem', transactionId, sku, name, category, price, quantity]);
            that._log('_addItem', args);
          });
          _analyticsJs(function () {
            if (that._ecommerceEnabled()) {
              $window.ga('ecommerce:addItem', {
                id: transactionId,
                name: name,
                sku: sku,
                category: category,
                price: price,
                quantity: quantity
              });
              that._log('ecommerce:addItem', args);
            }
          });
        };

```

**Comment by Jay031** [comment]
I also have trouble with the E-commerce, with single ánd multiple accounts.
When I add a product, checkout or transaction I don't get anything in Analytics.
The only thing that see is a click on "add to cart" in category "UX"

**Comment by justinsa** [comment]
I don't think the e-Commerce parts are designed to work with multiple accounts. They are pushing commands directly to the primary queue and not specifying any account token. This seems like an area that needs work then. In my previous verification I was verifying that the commands are being pushed to the appropriate queues when the methods are called, not that those are the correct commands to be issued for GA e-Commerce. I have limited knowledge of the e-commerce functionality in GA, so either I learn that, which could take a while given my schedule, or someone with existing knowledge helps determine what should actually be happening for the e-commerce functionality.
