### ISSUE TITLE
Issues with minification

### ISSUE THREAD

**Issue by czieler** [revolunet/angular-google-analytics#89]
Does anyone else have issues with using these files when minifying all angular files?  I keep getting unknown provider error.  I tried patching up just the provider to have brackets which looked like the obvious fix, but that doesn't seem to fix the issue.

**Comment by justinsa** [comment]
Hey @czieler, can you explain further what you are seeing and provide a code sample? For Angular to work correctly with minification you have to use the array designation style for controller, service, and directive definitions. e.g, 

```
this.$get = ['$document', '$location', '$log', '$rootScope', '$window', function ($document, $location, $log, $rootScope, $window) {
...
})];
```

**Comment by justinsa** [comment]
@czieler are you still experiencing this issue or can we close this?

**Comment by justinsa** [comment]
Closing issue as non-reproducible.
