### ISSUE TITLE
Changelog for v1?

### ISSUE THREAD

**Issue by binarykitchen** [revolunet/angular-google-analytics#93]
Are there any breaking changes??

**Comment by justinsa** [comment]
There are no breaking changes in v1, Everything changed was structural and not behavioral from the perspective of a user.

**Comment by binarykitchen** [comment]
understand but according to the semver philosophy it should be a breaking change, causing a major version bump.

**Comment by revolunet** [comment]
i published 1.0.0 because semver makes nosense if < 1.0.0 :
> the release 1.0.0 is considered the first stable release and the semver contract does not apply to releases before it.

**Comment by binarykitchen** [comment]
true that, all good then
