### ISSUE TITLE
Test / Build using CodeShip for repository

### ISSUE THREAD

**Issue by justinsa** [revolunet/angular-google-analytics#96]
@revolunet since you are the administrator of the repository you should add the free account from https://codeship.com to the repository. This can then run the tests on each PR and it can showing test run status for the PR.

I was going to set this up but I don't have admin privileges for the repository.

Also, if the production release build is automatic, then CodeShip might be able to be setup to do that whenever a commit gets to master. Something to consider.

**Comment by revolunet** [comment]
ok this is done ! thanks for this great initiative
