### ISSUE TITLE
Unknown provider: AnalyticsProviderProvider <- AnalyticsProvider

### ISSUE THREAD

**Issue by jrosseel** [revolunet/angular-google-analytics#97]
I get the error: Unknown provider: AnalyticsProviderProvider <- AnalyticsProvider when just including the script and injecting it into the application. 

Everything is fine in app.config, I'm able to configure the service just fine. But when I enter app.run, my application breaks down and gives me this error.

Any ideas on what might cause this?

My config settings: 
AnalyticsProvider.setAccount('UA-somecode');
AnalyticsProvider.trackPages(true);
AnalyticsProvider.trackUrlParams(true);
AnalyticsProvider.useDisplayFeatures(true);
AnalyticsProvider.ignoreFirstPageLoad(true);
AnalyticsProvider.useAnalytics(true);

**Comment by justinsa** [comment]
You should be calling it Analytics in your run block. Angular then looks for AnalyticsProvider to create the Analytics instance.

**Comment by jrosseel** [comment]
I see, thx!
