### ISSUE TITLE
Support advanced debugging for analytics

### ISSUE THREAD

**Issue by justinsa** [revolunet/angular-google-analytics#99]
https://developers.google.com/analytics/devguides/collection/analyticsjs/debugging

- [x] Analytics.js debugging snippet support
- [x] Analytics.js trace debugging configuration support

This functionality is only available for universal analytics.

**Comment by SimeonC** [comment]
There's a workaround for this with the chrome plugin here: https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna
